/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RouteSearchParamsRouteImport } from './routes/route-search-params'
import { Route as RoutePendingComponentRouteImport } from './routes/route-pendingComponent'
import { Route as RouteLoaderRouteImport } from './routes/route-loader'
import { Route as FormRouteImport } from './routes/form'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as IndexRouteImport } from './routes/index'

const RouteSearchParamsRoute = RouteSearchParamsRouteImport.update({
  id: '/route-search-params',
  path: '/route-search-params',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutePendingComponentRoute = RoutePendingComponentRouteImport.update({
  id: '/route-pendingComponent',
  path: '/route-pendingComponent',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteLoaderRoute = RouteLoaderRouteImport.update({
  id: '/route-loader',
  path: '/route-loader',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/form': typeof FormRoute
  '/route-loader': typeof RouteLoaderRoute
  '/route-pendingComponent': typeof RoutePendingComponentRoute
  '/route-search-params': typeof RouteSearchParamsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/form': typeof FormRoute
  '/route-loader': typeof RouteLoaderRoute
  '/route-pendingComponent': typeof RoutePendingComponentRoute
  '/route-search-params': typeof RouteSearchParamsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/form': typeof FormRoute
  '/route-loader': typeof RouteLoaderRoute
  '/route-pendingComponent': typeof RoutePendingComponentRoute
  '/route-search-params': typeof RouteSearchParamsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/form'
    | '/route-loader'
    | '/route-pendingComponent'
    | '/route-search-params'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/form'
    | '/route-loader'
    | '/route-pendingComponent'
    | '/route-search-params'
  id:
    | '__root__'
    | '/'
    | '/error'
    | '/form'
    | '/route-loader'
    | '/route-pendingComponent'
    | '/route-search-params'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorRoute: typeof ErrorRoute
  FormRoute: typeof FormRoute
  RouteLoaderRoute: typeof RouteLoaderRoute
  RoutePendingComponentRoute: typeof RoutePendingComponentRoute
  RouteSearchParamsRoute: typeof RouteSearchParamsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/route-search-params': {
      id: '/route-search-params'
      path: '/route-search-params'
      fullPath: '/route-search-params'
      preLoaderRoute: typeof RouteSearchParamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-pendingComponent': {
      id: '/route-pendingComponent'
      path: '/route-pendingComponent'
      fullPath: '/route-pendingComponent'
      preLoaderRoute: typeof RoutePendingComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-loader': {
      id: '/route-loader'
      path: '/route-loader'
      fullPath: '/route-loader'
      preLoaderRoute: typeof RouteLoaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorRoute: ErrorRoute,
  FormRoute: FormRoute,
  RouteLoaderRoute: RouteLoaderRoute,
  RoutePendingComponentRoute: RoutePendingComponentRoute,
  RouteSearchParamsRoute: RouteSearchParamsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
